### ISSUE TITLE
开启侧边栏的用户 的 用户ID怎么获取到？

### ISSUE THREAD

**Issue by Geeker-Pepsi** [wecom-sidebar/wecom-sidebar-docs#1]
我看官方API的描述说聊天侧边栏调用getcurexternaluserid就可以获取到当前外部联系人userid，但是其他的就没有过多描述了 相关的一些其他配置操作可以提示一下吗？感谢

**Comment by JslinSir** [comment]
第一步：判断打开场景
第二步：获取外部联系人

**Comment by haixiangyan** [comment]
没太懂这里的意思，直接用 

```js
wx.invoke('getCurExternalContact', {
        }, function(res){
        if(res.err_msg == "getCurExternalContact:ok"){
            userId  = res.userId ; //返回当前外部联系人userId
        }else {
            //错误处理
        }
    });
```

就可以了。

参考：https://open.work.weixin.qq.com/api/doc/90001/90144/91825

**Comment by Geeker-Pepsi** [comment]
好的，谢谢您😋



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Monster ***@***.***&gt;
发送时间: 2021年11月14日 00:58
收件人: wecom-sidebar/wecom-sidebar-docs ***@***.***&gt;
抄送: Geek-cola ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [wecom-sidebar/wecom-sidebar-docs] 开启侧边栏的用户 的 用户ID怎么获取到？ (Issue #1)
