### ISSUE TITLE
配置了多个企业微信的侧边栏，每个页面都需要授权吗？

### ISSUE THREAD

**Issue by connor-chl** [wecom-sidebar/wecom-sidebar-docs#2]
比如：我在我的企业微信配置了两个侧边栏tab，客户信息->http://a.com/a.html，跟进情况->http://a.com/b.html。获取页面数据的时候需要用到员工的id（打开侧边栏的这个人），是需要授权才能获得用户身份的，两个页面都需要去授权吗，还是只用授权一个页面，那另一个页面如何去到这个身份信息呢。

**Comment by connor-chl** [comment]
还有一种情况，我跟A客户聊天打开了侧边栏，会授权。然后再跟B客户聊天打开侧边栏，还会再次授权吗

**Comment by JslinSir** [comment]
看你前端代码怎么设计了，可以缓存登录态

**Comment by haixiangyan** [comment]
抱歉这么晚才看到，文档里的建议是将 userId 缓存到 cookie 里，这也是最推荐的方法，只有当重启企业微信的时候， cookie 才会被清掉。

具体可以看这里 https://open.work.weixin.qq.com/api/doc/90001/90143/91118 的最后那几点。
