### ISSUE TITLE
缓存登录态，切换企业微信问题

### ISSUE THREAD

**Issue by JslinSir** [wecom-sidebar/wecom-sidebar-docs#3]
由于登录态是存在 cookie 中，或者存在localStorage 中，每当我们 切换企业的时候就会出现问题，用户信息还是上一次的用户，不是当前企业的应用？你怎么办？

解决办法：我们知道，企微的Js-Sdk 的初始化是和企业绑定的，如果切换企业，这个时候，授权肯定会失败，我们可以根据授权失败的状态码，以及 是否当前存在缓存，来判断是否切换了企业，两者命中，重新走授权流程。

关于 企微的 缓存清除机制：每次APP 退出登录的时候，会自动清除 webView的缓存，cookie，localStorage

存在的问题：Pc端的企业微信，即使退出了，缓存依旧存在，需要手动清除，建议 Pc端每次进来都要走下授权

以上是我遇到的坑

**Comment by haixiangyan** [comment]
好建议，不过目前我们只针对一个企业来开发，所以这个情况还没遇到过。如果会有这样的问题，是需要根据 `err_msg` 和 cookie 缓存来判断是否要重新授权。
